### ISSUE TITLE
Psycopg2 error on RHEL 6

### ISSUE THREAD

**Issue by devrimgunduz** [keithf4/pg_bloat_check#10]
Hi,

I am getting this on RHEL 6. I cannot reproduce this on Fedora 24 box. They both have psycopg2 2.6.2:

$ pg_bloat_check.py  --create_stats_table
Traceback (most recent call last):
  File "/usr/bin/pg_bloat_check.py", line 5, in <module>
    import argparse, csv, json, psycopg2, sys
  File "/usr/lib64/python2.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: /usr/lib64/python2.6/site-packages/psycopg2/_psycopg.so: undefined symbol: lo_truncate64

Both machines are running 9.5.3.

Regards, Devrim

**Comment by devrimgunduz** [comment]
Ooops, sorry, local configuration error.
